spring.application.name=TermTrack-Backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/termtrack}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
application.security.jwt.secret-key=${JWT_SECRET_KEY:}
application.security.jwt.expiration=86400000